# Generated by Django 4.2.4 on 2023-09-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_cliente_endereco_alter_cliente_idade'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apelido', models.CharField(max_length=50)),
                ('ano', models.IntegerField()),
                ('modelo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=50)),
                ('cor', models.CharField(max_length=10)),
            ],
        ),
    ]
