# Generated by Django 4.2.4 on 2023-09-02 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_carro'),
    ]

    operations = [
        migrations.AddField(
            model_name='carro',
            name='dono',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='core.cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cliente',
            name='nome',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
